### ISSUE TITLE
Doc Versioning and wrong "Modified By"

### ISSUE THREAD

**Issue by rghariani** [exo-addons/onlyoffice#22]
Hello , 
we have incident with versionning and word "Modify By" , you can found in [this link](https://docs.google.com/document/d/1ecWQSW9W43MJm8WdVot40vWw3c4j_WHiZ4qkKgsItU0/edit) a steps of this issue. ( and in [this link ](https://drive.google.com/open?id=12Fsuzv0YD6HGg4O5PtlUyB96ehi41j2o)a video )

Thank you

**Comment by pnedonosko** [comment]
It is not an issue. It how Platform UI show node's checked-out state, read it as 'open' state. Within JCR versioning a node can be in checked-in (closed) and checked-out (open) states. When Onlyoffice editor saves the file, it opens the node if not already open, then it applies all the changes including dates and author of this save, next it closes the node to create a new version (it will appear with the date and modified by user that were just applied), finally it opens the node again (to let others to modify the node) - this open state will appear as _current version_ in eXo UI (in JCR spec it is named 'base version'), but this version not _yet created_ and we see a last user who did modified the file. 
Let's follow your steps now: Vincenzo created first version (and editor closed it) - eXo UI shows open state as version _2 (current version)_ with Vincenzo as last modifier, but at this point _only a single first version exists_ in the history. Then, Giuseppe edits the file, his save changes the content, dates and modified by user accordingly, these changes become a version 2, and node opens after this as a current version 3 where same dates/modifier as in v2 (v3 doesn't exist in fact - file in checked-out state in terms of JCR versioning). Next, Vincenzo restores version 1, this operation closes the current version, thus v3 appears with dates and modifier Giuseppe because it's a state leaved by this user, and current version become v4 with a state of restored v1.

**Comment by pnedonosko** [comment]
Versioning will be improved by #28, it may affect behaviour described here.
